### ISSUE TITLE
Build a Kotlin DSL related to Condition

### ISSUE THREAD

**Issue by icepeppermint** [line/conditional#3]
Methods such as not, and, or provided by the Condition class can be made more readable by using the Kotlin DSL.
So, build a Kotlin DSL to support this in the conditional-kotlin module.

**Comment by doljae** [comment]
Hello. I made a [simple PR](https://github.com/line/conditional/pull/4) about the issue 🙂

**Comment by icepeppermint** [comment]
@doljae got it. thanks :)
